name: "Сообщить о проблеме в переводе"
description: "Если что-то переведено неправильно."
labels: ["triage"]
body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Описание"
      description: "Опишите проблему как можно подробнее"

  - type: textarea
    id: dialogue
    attributes:
      label: "Строка диалога"
      description: "Напишите какая строка или какие строки вас беспокоят"
      placeholder: |
        Отборные ресурсы производятся благодаря стрессу. Так держать, Человек-Фонарь.
        Почему тут Человек-Фонарь, а не Человек-Паук?!

  - type: textarea
    id: screenshots
    attributes:
      label: "Скриншоты"
      description: |
        Если необходимо, добавьте скриншоты, чтобы помочь объяснить вашу проблему
        **Подсказка**: Вы можете прикрепить изображения щелкнув по области ниже, чтобы выделить её, а затем перетащив в нее файлы

